# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "Config reloaded!"

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux